# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8143ff90ac1bb45b051115520e5960e606d8f807ec90f3a7a8f495a8a16e0036d06b4dc8c8fab1fb55c98805b7c7866530ad33d1de1110807919ebfc4b37d792

test:
  secret_key_base: 33f79d460eef716583ccd5c858fbe523e86a314454fca3ca6d53ef465739ca8eb96bef0f2168bd70174c8126040e5cd9247e9c69810a9bb9525eb729ef137a99

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
